# Theme config.
languageCode = 'en-us'
title = "test"
contentdir = "content"
baseURL = "http://localhost:1313/"

[params]
    description = "test personal blog"
    home = "/"
    blog = "https://blog.test.com"
    email = "test@test.com"
    github = "test"
    twitter = "test"
    linkedin = "test"
    mastodon = "test"
    keybase = "test"
    reddit = "test"
    
