# Theme config.
languageCode = 'en-us'
title = "lbenicio"
contentdir = "content"


[params]
    github = "lbenicio"
    twitter = "lbenicio_"
    linkedin = "leonardo-benicio-1a55a1ba"
    mastodon = "lbenicio"
    description = "Leonardo Benicio personal blog"
    homepage = "http://localhost:1313/"
    home = "/"
    blog = "https://blog.lbenicio.dev"